package Vista;

import Datos.Documento;
import Datos.Oficina;
import Datos.Personal;
import Datos.TipoDocumento;
import Modelo.Modelo_Tabla_Documento;
import Negocio.DocumentoBo;
import Negocio.OficinaBo;
import Negocio.TipoDocBo;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Cristhian Millier Flores Pasapera
 * @gamail 7050423891@untrm.edu.pe
 * @telefono 934576998
 */
public class frmDocumento extends javax.swing.JInternalFrame {

    private String cargo = "default";
    private int id = 0;
    private Modelo_Tabla_Documento MTD = new Modelo_Tabla_Documento();
    private Documento objD = null;
    private TipoDocumento objTD = null;
    private Oficina objO = null;

    private String nroDoc;
    private String observacion;
    private String categoria;
    private String nroArchivo;

    /**
     * Creates new form frmDocumento
     */
    public frmDocumento() {
        initComponents();
        this.botonos();
        this.cargarTabla();
        this.definir_tamaño_columna();
        this.cargarCombox();
        this.controles(false);

        this.txtFechaDoc.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.tablaDocumento.setRowHeight(25);
        this.cargarFecha();
        this.cargarFechaCalendar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtRecibe = new javax.swing.JRadioButton();
        txtRemite = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNroDoc = new javax.swing.JTextField();
        txtFechaDoc = new com.toedter.calendar.JDateChooser();
        comboTipoDoc = new javax.swing.JComboBox<>();
        comboOficina = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDocumento = new javax.swing.JTable();
        txtFechaBusca = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboOficinaBusc = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAsunto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObvesrvacion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtNroArchivo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFechaRecibe = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Documento");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documento.png"))); // NOI18N
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigo-limpio.png"))); // NOI18N
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        grupo.add(txtRecibe);
        txtRecibe.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtRecibe.setForeground(new java.awt.Color(255, 255, 255));
        txtRecibe.setText("Recibida");
        txtRecibe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        grupo.add(txtRemite);
        txtRemite.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtRemite.setForeground(new java.awt.Color(255, 255, 255));
        txtRemite.setText("Remitida");
        txtRemite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363)
                .addComponent(txtRecibe)
                .addGap(116, 116, 116)
                .addComponent(txtRemite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRecibe)
                        .addComponent(txtRemite))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardar)
                        .addComponent(btnNuevo)
                        .addComponent(btnLimpiar)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Indicativo (Nro):");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clase (Tipo):");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Clasif. (Sección):");

        txtNroDoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNroDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroDocKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroDocKeyTyped(evt);
            }
        });

        txtFechaDoc.setDateFormatString("yyyy-MM-dd");
        txtFechaDoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFechaDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaDocKeyPressed(evt);
            }
        });

        comboTipoDoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboTipoDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboTipoDocKeyPressed(evt);
            }
        });

        comboOficina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboOficina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboOficina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboOficinaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(comboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTextFieldDateEditor editor = (JTextFieldDateEditor) txtFechaDoc.getDateEditor();
        editor.setEditable(false);
        AutoCompleteDecorator.decorate(comboTipoDoc);
        AutoCompleteDecorator.decorate(comboOficina);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documentos Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar-codigo.png"))); // NOI18N
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        tablaDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaDocumento.setModel(this.MTD);
        tablaDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(tablaDocumento);

        txtFechaBusca.setDateFormatString("yyyy-MM-dd");
        txtFechaBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha Recp:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sección:");

        comboOficinaBusc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboOficinaBusc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recargarTabla.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboOficinaBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboOficinaBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTextFieldDateEditor editor1 = (JTextFieldDateEditor) txtFechaBusca.getDateEditor();
        editor1.setEditable(false);
        AutoCompleteDecorator.decorate(comboOficinaBusc);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Extra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        txtAsunto.setColumns(20);
        txtAsunto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAsunto.setLineWrap(true);
        txtAsunto.setRows(5);
        txtAsunto.setWrapStyleWord(true);
        txtAsunto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAsunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAsuntoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtAsunto);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Asunto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destinatario:");

        txtDestino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDestinoKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha Recepción:");

        txtObvesrvacion.setColumns(20);
        txtObvesrvacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtObvesrvacion.setLineWrap(true);
        txtObvesrvacion.setRows(5);
        txtObvesrvacion.setWrapStyleWord(true);
        txtObvesrvacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObvesrvacionKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtObvesrvacion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Archivo N°:");

        txtNroArchivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNroArchivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroArchivoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroArchivoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Observaciónes:");

        txtFechaRecibe.setEditable(false);
        txtFechaRecibe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiar();
        this.cargarFechaCalendar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limpiar();
        this.cargarTabla();
        this.controles(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.controles(true);
        this.limpiar();
        this.cargarTabla();
        this.limpiarBusqueda();
        this.cargarFechaCalendar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.clicEditar();
        this.limpiarBusqueda();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void comboTipoDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboTipoDocKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.txtNroDoc.requestFocus();
        }
    }//GEN-LAST:event_comboTipoDocKeyPressed

    private void txtNroDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDocKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.txtFechaDoc.requestFocus();
        }
    }//GEN-LAST:event_txtNroDocKeyPressed

    private void txtNroDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDocKeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_txtNroDocKeyTyped

    private void txtFechaDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaDocKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.comboOficina.requestFocus();
        }
    }//GEN-LAST:event_txtFechaDocKeyPressed

    private void comboOficinaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboOficinaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.txtDestino.requestFocus();
        }
    }//GEN-LAST:event_comboOficinaKeyPressed

    private void txtDestinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.txtAsunto.requestFocus();
        }
    }//GEN-LAST:event_txtDestinoKeyPressed

    private void txtNroArchivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroArchivoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.txtObvesrvacion.requestFocus();
        }
    }//GEN-LAST:event_txtNroArchivoKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.guardar();
        this.cargarFechaCalendar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNroArchivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroArchivoKeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_txtNroArchivoKeyTyped

    private void txtAsuntoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAsuntoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.txtNroArchivo.requestFocus();
        }
    }//GEN-LAST:event_txtAsuntoKeyPressed

    private void txtObvesrvacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObvesrvacionKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.btnGuardar.doClick();
        }
    }//GEN-LAST:event_txtObvesrvacionKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.clicBuscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.cargarTabla();
        this.limpiarBusqueda();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Oficina> comboOficina;
    private javax.swing.JComboBox<Oficina> comboOficinaBusc;
    private javax.swing.JComboBox<TipoDocumento> comboTipoDoc;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaDocumento;
    private javax.swing.JTextArea txtAsunto;
    private javax.swing.JTextField txtDestino;
    private com.toedter.calendar.JDateChooser txtFechaBusca;
    private com.toedter.calendar.JDateChooser txtFechaDoc;
    private javax.swing.JTextField txtFechaRecibe;
    private javax.swing.JTextField txtNroArchivo;
    private javax.swing.JTextField txtNroDoc;
    private javax.swing.JTextArea txtObvesrvacion;
    private javax.swing.JRadioButton txtRecibe;
    private javax.swing.JRadioButton txtRemite;
    // End of variables declaration//GEN-END:variables

    public void setCargo(String cargo, int id) {
        this.cargo = cargo;
        this.id = id;
    }

    private void botonos() {
        this.btnCancelar.setOpaque(false);
        this.btnCancelar.setContentAreaFilled(false);
        this.btnCancelar.setBorderPainted(false);
        this.btnCancelar.setToolTipText("Cancelar");

        this.btnNuevo.setOpaque(false);
        this.btnNuevo.setContentAreaFilled(false);
        this.btnNuevo.setBorderPainted(false);
        this.btnNuevo.setToolTipText("Nuevo");

        this.btnGuardar.setOpaque(false);
        this.btnGuardar.setContentAreaFilled(false);
        this.btnGuardar.setBorderPainted(false);
        this.btnGuardar.setToolTipText("Guardar");

        this.btnLimpiar.setOpaque(false);
        this.btnLimpiar.setContentAreaFilled(false);
        this.btnLimpiar.setBorderPainted(false);
        this.btnLimpiar.setToolTipText("Limpiar");

        this.btnSalir.setOpaque(false);
        this.btnSalir.setContentAreaFilled(false);
        this.btnSalir.setBorderPainted(false);
        this.btnSalir.setToolTipText("Salir");

        this.btnEditar.setOpaque(false);
        this.btnEditar.setContentAreaFilled(false);
        this.btnEditar.setBorderPainted(false);
        this.btnEditar.setToolTipText("Editar");

        this.btnBuscar.setOpaque(false);
        this.btnBuscar.setContentAreaFilled(false);
        this.btnBuscar.setBorderPainted(false);
        this.btnBuscar.setToolTipText("Buscar");

        this.btnActualizar.setOpaque(false);
        this.btnActualizar.setContentAreaFilled(false);
        this.btnActualizar.setBorderPainted(false);
        this.btnActualizar.setToolTipText("Actualizar Tabla");
    }

    private void cargarTabla() {
        try {
            ArrayList<Documento> ltsDocumento = DocumentoBo.obtenerListaDocGeneral(cargo);
            MTD.setListado_Documento(ltsDocumento);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    private void definir_tamaño_columna() {
        TableColumnModel columnModel = this.tablaDocumento.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(450);
        columnModel.getColumn(3).setPreferredWidth(150);

        this.tablaDocumento.getTableHeader().setFont(new Font("Tahoma", 1, 12));
        ((DefaultTableCellRenderer) this.tablaDocumento.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
    }

    private void cargarCombox() {
        this.comboOficina.removeAllItems();
        Oficina objOficina = new Oficina();
        objOficina.setNombre("--Seleccione--");
        this.comboOficina.addItem(objOficina);
        this.comboOficinaBusc.addItem(objOficina);

        this.comboTipoDoc.removeAllItems();
        TipoDocumento objTP = new TipoDocumento();
        objTP.setNombre("--Seleccione--");
        this.comboTipoDoc.addItem(objTP);

        try {
            OficinaBo.obtenerListaComboOficina(this.comboOficina, cargo);
            TipoDocBo.obtenerListaComboTipDoc(this.comboTipoDoc, cargo);
            OficinaBo.obtenerListaComboOficina(this.comboOficinaBusc, cargo);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void obtenerDatosCombo() {
        if (this.comboOficina.getItemAt(this.comboOficina.getSelectedIndex()) != null) {
            this.objO = this.comboOficina.getItemAt(this.comboOficina.getSelectedIndex());
        }

        if (this.comboTipoDoc.getItemAt(this.comboTipoDoc.getSelectedIndex()) != null) {
            this.objTD = this.comboTipoDoc.getItemAt(this.comboTipoDoc.getSelectedIndex());
        }
    }

    private void controles(boolean estado) {
        this.comboOficina.setEnabled(estado);
        this.comboTipoDoc.setEnabled(estado);
        this.txtNroDoc.setEnabled(estado);
        this.txtFechaDoc.setEnabled(estado);
        this.txtDestino.setEnabled(estado);
        this.txtAsunto.setEnabled(estado);
        this.txtNroArchivo.setEnabled(estado);
        this.txtObvesrvacion.setEnabled(estado);
        this.btnGuardar.setEnabled(estado);
        this.btnLimpiar.setEnabled(estado);
        this.btnCancelar.setEnabled(estado);
        this.txtRecibe.setEnabled(estado);
        this.txtRemite.setEnabled(estado);
        this.txtFechaRecibe.setEnabled(estado);

        this.btnNuevo.setEnabled(!estado);
        this.tablaDocumento.setEnabled(!estado);
        this.comboOficinaBusc.setEnabled(!estado);
        this.txtFechaBusca.setEnabled(!estado);
        this.btnEditar.setEnabled(!estado);
        this.btnBuscar.setEnabled(!estado);
        this.btnActualizar.setEnabled(!estado);
        
        if (estado) {
            tablaDocumento.setBackground(new java.awt.Color(255, 102, 102));
        } else {
            tablaDocumento.setBackground(new java.awt.Color(255, 255, 255));
        }
    }

    private void limpiar() {
        this.comboOficina.setSelectedIndex(0);
        this.comboTipoDoc.setSelectedIndex(0);
        this.txtNroDoc.setText("");
        this.txtFechaDoc.setCalendar(null);
        this.txtDestino.setText("");
        this.txtAsunto.setText("");
        this.txtNroArchivo.setText("");
        this.txtObvesrvacion.setText("");
        this.grupo.clearSelection();

        objD = null;
        objTD = null;
        objO = null;
        nroDoc = null;
        observacion = null;
        categoria = null;
        nroArchivo = null;
    }

    private void cargarDatos(Documento objD) throws ParseException {
        String fecha = objD.getFechaDoc();
        String anio = fecha.substring(0, 4);
        String mes = fecha.substring(5, 7);
        String dia = fecha.substring(8, 10);
        java.util.Date fechaParseada = new SimpleDateFormat("yyyy-MM-dd").parse(anio + "-" + mes + "-" + dia);

        this.comboTipoDoc.getModel().setSelectedItem(objD.getIdTipDoc());
        this.comboOficina.getModel().setSelectedItem(objD.getIdSeccion());
        this.txtNroDoc.setText(objD.getNroDoc());
        this.txtFechaDoc.setDate(fechaParseada);
        this.txtDestino.setText(objD.getDestinatario());
        this.txtAsunto.setText(objD.getAsunto());
        this.txtNroArchivo.setText(objD.getArchivoNro());
        this.txtObvesrvacion.setText(objD.getObservaciones());
        this.txtFechaRecibe.setText(objD.getFechaRecibe());

        if (objD.getCategoria().equals("Recibida")) {
            this.txtRecibe.setSelected(true);
        } else {
            this.txtRemite.setSelected(true);
        }

        this.objO = objD.getIdSeccion();
        this.objTD = objD.getIdTipDoc();
    }

    private void validar_llenado(java.awt.event.KeyEvent evt, int opc) {
        //opc: 1 es para ingresar solo números
        //opc: 2 es para ingresar solo letras
        char validar = evt.getKeyChar();
        if (opc == 1) {
            if (Character.isLetter(validar) && validar != KeyEvent.VK_SPACE
                    && validar != KeyEvent.VK_ENTER) {
                getToolkit().beep(); //sonido de alerta
                evt.consume();
            }
        }
        if (opc == 2) {
            if (Character.isDigit(validar) && validar != KeyEvent.VK_SPACE
                    && validar != KeyEvent.VK_ENTER) {
                getToolkit().beep(); //sonido de alerta
                evt.consume();
            }
        }
    }

    private boolean general() {
        if (this.comboTipoDoc.getSelectedIndex() == 0 || this.txtDestino.getText().trim().equals("")
                || ((JTextField) this.txtFechaDoc.getDateEditor().getUiComponent()).getText().trim().equals("")
                || this.comboOficina.getSelectedIndex() == 0 || this.txtAsunto.getText().trim().equals("")) {
            return false;

        } else {
            return true;
        }
    }

    private void nroDocObver() {
        if (this.txtNroDoc.getText().trim().equals("")) {
            this.nroDoc = "S/N";
        } else {
            this.nroDoc = this.txtNroDoc.getText().trim();
        }
        if (this.txtObvesrvacion.getText().trim().equals("")) {
            this.observacion = "S/O";
        } else {
            this.observacion = this.txtObvesrvacion.getText().trim();
        }
        if (this.txtRecibe.isSelected()) {
            this.categoria = "Recibida";
        }
        if (this.txtRemite.isSelected()) {
            this.categoria = "Remitida";
        }
        if (this.txtNroArchivo.getText().trim().equals("")) {
            this.nroArchivo = "S/N";
        } else {
            this.nroArchivo = this.txtNroArchivo.getText().trim();
        }
    }

    private void guardar() {
        if (this.txtRecibe.isSelected() || this.txtRemite.isSelected()) {
            if (this.general()) {
                this.nroDocObver();
                this.obtenerDatosCombo();
                Documento objDoc = new Documento(0, this.nroDoc, ((JTextField) this.txtFechaDoc.getDateEditor().getUiComponent()).getText(),
                        this.txtAsunto.getText(), this.txtDestino.getText(), this.txtFechaRecibe.getText(), this.nroArchivo,
                        this.observacion, this.categoria, this.objO, this.objTD, new Personal(this.id));
                try {
                    if (this.objD == null) {
                        if (DocumentoBo.grabarDocumento(objDoc, cargo)) {
                            JOptionPane.showMessageDialog(this, "Se Registró Correctamente", "MENSAJE --> DOCUMENTO", JOptionPane.INFORMATION_MESSAGE);
                            if (this.categoria.equals("Remitida")) {
                                DocumentoBo.grabarPerRecib(this.id, DocumentoBo.ultimoIdDoc(cargo), cargo);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No se pudo Registrar", "MENSAJE --> DOCUMENTO", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        objDoc.setIdDocumento(this.objD.getIdDocumento());
                        if (DocumentoBo.modificarDocumento(objDoc, cargo)) {
                            JOptionPane.showMessageDialog(this, "Se Modificó Correctamente", "MENSAJE --> DOCUMENTO", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "No se pudo Modificar", "MENSAJE --> DOCUMENTO", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
                this.limpiar();
                this.limpiarBusqueda();
                this.controles(false);
                this.cargarTabla();
                this.cargarFecha();
            } else {
                JOptionPane.showMessageDialog(this, "Verifique que los campos correspondientes esten llenado correctamente.", "MENSAJE --> DOCUMENTO", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Usted no a selecionado el tipo de correspondencia.", "MENSAJE --> DOCUMENTO", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void clicEditar() {
        this.comboOficinaBusc.setSelectedIndex(0);
        int fila = this.tablaDocumento.getSelectedRow();
        if (fila != -1) {
            this.objD = MTD.getDocumento(fila);
            try {
                this.cargarDatos(objD);
                this.controles(true);
                this.cargarTabla();
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Usted no a seleccionado un campo en la tabla.", "MENSAJE --> PERSONAL", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clicBuscar() {
        Oficina objBusc = new Oficina();
        ArrayList<Documento> ltsDocumento = null;
        if (this.comboOficinaBusc.getItemAt(this.comboOficinaBusc.getSelectedIndex()) != null) {
            objBusc = this.comboOficinaBusc.getItemAt(this.comboOficinaBusc.getSelectedIndex());
        }
        try {
            if (this.comboOficinaBusc.getSelectedIndex() != 0 || (!((JTextField) this.txtFechaBusca.getDateEditor().getUiComponent()).getText().equals(""))) {
                if (this.comboOficinaBusc.getSelectedIndex() != 0 && ((JTextField) this.txtFechaBusca.getDateEditor().getUiComponent()).getText().equals("")) {
                    ltsDocumento = DocumentoBo.obtenerListaOficinaRecibe(objBusc.getIdOficina(), cargo);
                }
                if (this.comboOficinaBusc.getSelectedIndex() == 0 && (!((JTextField) this.txtFechaBusca.getDateEditor().getUiComponent()).getText().equals(""))) {
                    ltsDocumento = DocumentoBo.obtenerListaFechaRecpRecibe((String) ((JTextField) this.txtFechaBusca.getDateEditor().getUiComponent()).getText(), cargo);
                }
                if (this.comboOficinaBusc.getSelectedIndex() != 0 && (!((JTextField) this.txtFechaBusca.getDateEditor().getUiComponent()).getText().equals(""))) {
                    ltsDocumento = DocumentoBo.obtenerListaFechaRecpOficinaRecibe(objBusc.getIdOficina(), ((JTextField) this.txtFechaBusca.getDateEditor().getUiComponent()).getText(), cargo);
                }
                MTD.setListado_Documento(ltsDocumento);
                if (ltsDocumento.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No se han encontrado documentos según lo especificado.", "MENSAJE --> BUSCAR DOC.", JOptionPane.INFORMATION_MESSAGE);
                    this.cargarTabla();
                }
                this.limpiar();
                this.limpiarBusqueda();
            } else {
                JOptionPane.showMessageDialog(this, "Usted no a especificado como realizar la busqueda.", "MENSAJE --> BUSCAR DOC.", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void cargarFecha() {
        Calendar cal = Calendar.getInstance();
        Timestamp fecha_hora = new Timestamp(cal.getTimeInMillis());
        String fechaSistema = String.valueOf(fecha_hora);
        this.txtFechaRecibe.setText(fechaSistema.substring(0, 10));
    }

    private void limpiarBusqueda() {
        this.comboOficinaBusc.setSelectedIndex(0);
        this.txtFechaBusca.setCalendar(null);
    }
    
    private void cargarFechaCalendar(){
        Calendar cal = Calendar.getInstance();
        this.txtFechaBusca.setCalendar(cal);
        this.txtFechaDoc.setCalendar(cal);
    }
}
