package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Cristhian Millier Flores Pasapera
 * @gamail 7050423891@untrm.edu.pe
 * @telefono 934576998
 */
public class frmPrincipal extends javax.swing.JFrame {

    private String cargo;
    private int id;
    private frmGrado frmG = null;
    private frmPersonal frmP = null;
    private frmDocumento frmD = null;
    private frmSeccion frmS = null;
    private frmTipoDocumento frmTP = null;
    private frmDocRecibido frmDR = null;
    private frmRepFecha frmRPF = null;
    private frmBuscarDoc frmBD = null;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.botones();

        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setIconImage(getIconImage());
    }

    //Icono del Frame
    @Override
    public Image getIconImage() {
        Image image = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/sexta.png"));
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Maestro = new javax.swing.JMenu();
        Grado = new javax.swing.JMenuItem();
        Oficina = new javax.swing.JMenuItem();
        Personal = new javax.swing.JMenuItem();
        TipoDocumento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();
        Operaciones = new javax.swing.JMenu();
        buscarDoc = new javax.swing.JMenuItem();
        Documento = new javax.swing.JMenuItem();
        DocRecibido = new javax.swing.JMenuItem();
        Reporte = new javax.swing.JMenu();
        reportFecha = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEXTA BRIGADA DE SELVA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1506, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        Maestro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/opciones.png"))); // NOI18N
        Maestro.setText("Maestro");
        Maestro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Maestro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        Grado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Grado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grado.png"))); // NOI18N
        Grado.setText("Grado");
        Grado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradoActionPerformed(evt);
            }
        });
        Maestro.add(Grado);

        Oficina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Oficina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajar.png"))); // NOI18N
        Oficina.setText("Sección");
        Oficina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Oficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OficinaActionPerformed(evt);
            }
        });
        Maestro.add(Oficina);

        Personal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Personal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/soldado.png"))); // NOI18N
        Personal.setText("Personal");
        Personal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalActionPerformed(evt);
            }
        });
        Maestro.add(Personal);

        TipoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipo-de-archivo.png"))); // NOI18N
        TipoDocumento.setText("Tipo Documento");
        TipoDocumento.setToolTipText("");
        TipoDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDocumentoActionPerformed(evt);
            }
        });
        Maestro.add(TipoDocumento);
        Maestro.add(jSeparator1);

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Maestro.add(Salir);

        jMenuBar1.add(Maestro);

        Operaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/management.png"))); // NOI18N
        Operaciones.setText("Operaciones");
        Operaciones.setToolTipText("");
        Operaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Operaciones.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        buscarDoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarDocmento.png"))); // NOI18N
        buscarDoc.setText("Buscar Documento");
        buscarDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDocActionPerformed(evt);
            }
        });
        Operaciones.add(buscarDoc);

        Documento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Documento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documentos.png"))); // NOI18N
        Documento.setText("Correspondencia");
        Documento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentoActionPerformed(evt);
            }
        });
        Operaciones.add(Documento);

        DocRecibido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DocRecibido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/abierto.png"))); // NOI18N
        DocRecibido.setText("Recibir Documento");
        DocRecibido.setToolTipText("");
        DocRecibido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DocRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocRecibidoActionPerformed(evt);
            }
        });
        Operaciones.add(DocRecibido);

        jMenuBar1.add(Operaciones);

        Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        Reporte.setText("Reporte");
        Reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reporte.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        reportFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reportFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notas.png"))); // NOI18N
        reportFecha.setText("Por Fechas");
        reportFecha.setToolTipText("");
        reportFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportFechaActionPerformed(evt);
            }
        });
        Reporte.add(reportFecha);

        jMenuBar1.add(Reporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
        frmLogin login = new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalActionPerformed
        if (frmP != null) {
            frmP.dispose();
        }
        frmP = new frmPersonal();
        frmP.setCargo(cargo, id);
        this.PanelPrincipal.add(frmP);
        Dimension desktopSize = this.PanelPrincipal.getSize();
        Dimension FrameSize = frmP.getSize();
        frmP.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmP.setVisible(true);
    }//GEN-LAST:event_PersonalActionPerformed

    private void OficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OficinaActionPerformed
        if (frmS != null) {
            frmS.dispose();
        }
        frmS = new frmSeccion();
        frmS.setCargo(cargo);
        this.PanelPrincipal.add(frmS);
        Dimension desktopSize = this.PanelPrincipal.getSize();
        Dimension FrameSize = frmS.getSize();
        frmS.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmS.setVisible(true);
    }//GEN-LAST:event_OficinaActionPerformed

    private void TipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDocumentoActionPerformed
        if (frmTP != null) {
            frmTP.dispose();
        }
        frmTP = new frmTipoDocumento();
        frmTP.setCargo(cargo);
        this.PanelPrincipal.add(frmTP);
        Dimension desktopSize = this.PanelPrincipal.getSize();
        Dimension FrameSize = frmTP.getSize();
        frmTP.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmTP.setVisible(true);
    }//GEN-LAST:event_TipoDocumentoActionPerformed

    private void DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentoActionPerformed
        if (frmD != null) {
            frmD.dispose();
        }
        frmD = new frmDocumento();
        frmD.setCargo(cargo, id);
        this.PanelPrincipal.add(frmD);
        Dimension desktopSize = this.PanelPrincipal.getSize();
        Dimension FrameSize = frmD.getSize();
        frmD.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmD.setVisible(true);
    }//GEN-LAST:event_DocumentoActionPerformed

    private void GradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradoActionPerformed
        if (frmG != null) {
            frmG.dispose();
        }
        frmG = new frmGrado();
        frmG.setCargo(cargo);
        this.PanelPrincipal.add(frmG);
        Dimension desktopSize = this.PanelPrincipal.getSize();
        Dimension FrameSize = frmG.getSize();
        frmG.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmG.setVisible(true);
    }//GEN-LAST:event_GradoActionPerformed

    private void DocRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocRecibidoActionPerformed
        if (frmDR != null) {
            frmDR.dispose();
        }
        frmDR = new frmDocRecibido();
        frmDR.setCargo(cargo, id);
        this.PanelPrincipal.add(frmDR);
        Dimension desktopSize = this.PanelPrincipal.getSize();
        Dimension FrameSize = frmDR.getSize();
        frmDR.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmDR.setVisible(true);
    }//GEN-LAST:event_DocRecibidoActionPerformed

    private void reportFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportFechaActionPerformed
        if (frmRPF != null) {
            frmRPF.dispose();
        }
        frmRPF = new frmRepFecha();
        frmRPF.setCargo(cargo);
        this.PanelPrincipal.add(frmRPF);
        Dimension desktopSize = this.PanelPrincipal.getSize();
        Dimension FrameSize = frmRPF.getSize();
        frmRPF.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmRPF.setVisible(true);
    }//GEN-LAST:event_reportFechaActionPerformed

    private void buscarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDocActionPerformed
        if (frmBD != null) {
            frmBD.dispose();
        }
        frmBD = new frmBuscarDoc();
        frmBD.setCargo(cargo);
        this.PanelPrincipal.add(frmBD);
        Dimension desktopSize = this.PanelPrincipal.getSize();
        Dimension FrameSize = frmBD.getSize();
        frmBD.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmBD.setVisible(true);
    }//GEN-LAST:event_buscarDocActionPerformed

    public void setCargo(String cargo, int id) {
        this.cargo = cargo;
        this.id = id;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DocRecibido;
    private javax.swing.JMenuItem Documento;
    private javax.swing.JMenuItem Grado;
    private javax.swing.JMenu Maestro;
    private javax.swing.JMenuItem Oficina;
    private javax.swing.JMenu Operaciones;
    private javax.swing.JDesktopPane PanelPrincipal;
    private javax.swing.JMenuItem Personal;
    private javax.swing.JMenu Reporte;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem TipoDocumento;
    private javax.swing.JMenuItem buscarDoc;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem reportFecha;
    // End of variables declaration//GEN-END:variables

    void Permisos(String seccion) {
        switch (seccion) {
            case "SETEL":
                this.setel(true);
                break;
            case "OPB":
                this.OPB(false);
                break;
            default:
                this.todasOficinas(false);
                break;
        }
    }

    private void botones() {
        this.Operaciones.setToolTipText(null);
        this.Maestro.setToolTipText(null);
        this.Reporte.setToolTipText(null);

        this.Grado.setToolTipText(null);
        this.Oficina.setToolTipText(null);
        this.Personal.setToolTipText(null);
        this.TipoDocumento.setToolTipText(null);
        this.Salir.setToolTipText(null);
        this.buscarDoc.setToolTipText(null);
        this.Documento.setToolTipText(null);
        this.DocRecibido.setToolTipText(null);
        this.reportFecha.setToolTipText(null);
    }

    private void OPB(boolean estado) {
        this.Grado.setEnabled(estado);
        this.Personal.setEnabled(estado);
        this.DocRecibido.setEnabled(estado);
        this.Oficina.setEnabled(!estado);
        this.TipoDocumento.setEnabled(!estado);
        this.Documento.setEnabled(!estado);
        this.buscarDoc.setEnabled(!estado);
        this.reportFecha.setEnabled(!estado);

        this.Grado.setVisible(estado);
        this.Personal.setVisible(estado);
        this.DocRecibido.setVisible(estado);
        this.Oficina.setVisible(!estado);
        this.TipoDocumento.setVisible(!estado);
        this.Documento.setVisible(!estado);
        this.buscarDoc.setVisible(!estado);
        this.reportFecha.setVisible(!estado);
    }

    private void todasOficinas(boolean estado) {
        this.Reporte.setEnabled(estado);
        this.TipoDocumento.setEnabled(estado);
        this.Grado.setEnabled(estado);
        this.Oficina.setEnabled(estado);
        this.Personal.setEnabled(estado);
        this.Documento.setEnabled(estado);
        this.buscarDoc.setEnabled(estado);
        this.DocRecibido.setEnabled(!estado);

        this.Reporte.setVisible(estado);
        this.TipoDocumento.setVisible(estado);
        this.Grado.setVisible(estado);
        this.Oficina.setVisible(estado);
        this.Personal.setVisible(estado);
        this.Documento.setVisible(estado);
        this.buscarDoc.setVisible(estado);
        this.DocRecibido.setVisible(!estado);
    }

    private void setel(boolean estado) {
        this.Grado.setEnabled(estado);
        this.Oficina.setEnabled(estado);
        this.Personal.setEnabled(estado);
        this.TipoDocumento.setEnabled(estado);
        this.Documento.setEnabled(estado);
        this.buscarDoc.setEnabled(estado);
        this.DocRecibido.setEnabled(estado);
        this.reportFecha.setEnabled(estado);

        this.Grado.setVisible(estado);
        this.Oficina.setVisible(estado);
        this.Personal.setVisible(estado);
        this.TipoDocumento.setVisible(estado);
        this.Documento.setVisible(estado);
        this.buscarDoc.setVisible(estado);
        this.DocRecibido.setVisible(estado);
        this.reportFecha.setVisible(estado);
    }
}
