package Vista;

import Datos.Oficina;
import Negocio.OficinaBo;
import Reporte.RepFech;
import Reporte.RepFechCat;
import Reporte.RepFechRanCat;
import Reporte.RepFechRanCatSecc;
import Reporte.RepFechRanSecc;
import Reporte.RepFechSecc;
import Reporte.RepFechRang;
import Reporte.RepFechSeccCat;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Cursor;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Cristhian Millier Flores Pasapera
 * @gamail 7050423891@untrm.edu.pe
 * @telefono 934576998
 */
public class frmRepFecha extends javax.swing.JInternalFrame {

    private String cargo = "default";
    private Oficina objO = null;
    private String categoria = null;

    /**
     * Creates new form frmRepFecha
     */
    public frmRepFecha() {
        initComponents();
        this.botones();
        this.cargarCombox();

        this.setSize(new java.awt.Dimension(625, 320));
        this.panelFechEspc.setVisible(false);
        this.panelRangFec.setVisible(false);
        this.txtFechaEspc.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.txtFechaRang1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.txtFechaRang2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        botonGrupo1 = new javax.swing.ButtonGroup();
        botonGrupo2 = new javax.swing.ButtonGroup();
        panelGeneral = new javax.swing.JPanel();
        panelFechEspc = new javax.swing.JPanel();
        btnGenerarRep1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboOficina1 = new javax.swing.JComboBox<>();
        txtFechaEspc = new com.toedter.calendar.JDateChooser();
        recibida1 = new javax.swing.JRadioButton();
        remitida1 = new javax.swing.JRadioButton();
        btnFechaEspc = new javax.swing.JRadioButton();
        btnRangoFech = new javax.swing.JRadioButton();
        panelRangFec = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaRang1 = new com.toedter.calendar.JDateChooser();
        txtFechaRang2 = new com.toedter.calendar.JDateChooser();
        btnGenerarRep2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboOficina2 = new javax.swing.JComboBox<>();
        recibida2 = new javax.swing.JRadioButton();
        remitida2 = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Reporte por Fechas");
        setPreferredSize(new java.awt.Dimension(625, 270));

        panelGeneral.setBackground(new java.awt.Color(0, 102, 102));
        panelGeneral.setAutoscrolls(true);

        panelFechEspc.setBackground(new java.awt.Color(0, 153, 153));

        btnGenerarRep1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerarRep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finanzas-y-negocios.png"))); // NOI18N
        btnGenerarRep1.setText("Generar Reporte");
        btnGenerarRep1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRep1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sección:");

        comboOficina1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboOficina1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtFechaEspc.setDateFormatString("yyyy-MM-dd");
        txtFechaEspc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        botonGrupo1.add(recibida1);
        recibida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recibida1.setForeground(new java.awt.Color(255, 255, 255));
        recibida1.setText("RECIBIDA");
        recibida1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botonGrupo1.add(remitida1);
        remitida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remitida1.setForeground(new java.awt.Color(255, 255, 255));
        remitida1.setText("REMITIDA");
        remitida1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelFechEspcLayout = new javax.swing.GroupLayout(panelFechEspc);
        panelFechEspc.setLayout(panelFechEspcLayout);
        panelFechEspcLayout.setHorizontalGroup(
            panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechEspcLayout.createSequentialGroup()
                .addGroup(panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechEspcLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFechEspcLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboOficina1, 0, 191, Short.MAX_VALUE)
                            .addComponent(txtFechaEspc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelFechEspcLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(recibida1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarRep1)
                    .addComponent(remitida1))
                .addGap(27, 27, 27))
        );
        panelFechEspcLayout.setVerticalGroup(
            panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechEspcLayout.createSequentialGroup()
                .addGroup(panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechEspcLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechEspcLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtFechaEspc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboOficina1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFechEspcLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnGenerarRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelFechEspcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recibida1)
                    .addComponent(remitida1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        AutoCompleteDecorator.decorate(comboOficina1);
        JTextFieldDateEditor editor = (JTextFieldDateEditor) txtFechaEspc.getDateEditor();
        editor.setEditable(false);

        grupo1.add(btnFechaEspc);
        btnFechaEspc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFechaEspc.setForeground(new java.awt.Color(255, 255, 255));
        btnFechaEspc.setText("FECHA ESPECÍFICA");
        btnFechaEspc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechaEspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaEspcActionPerformed(evt);
            }
        });

        grupo1.add(btnRangoFech);
        btnRangoFech.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRangoFech.setForeground(new java.awt.Color(255, 255, 255));
        btnRangoFech.setText("RANGO DE FECHAS");
        btnRangoFech.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRangoFech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRangoFechActionPerformed(evt);
            }
        });

        panelRangFec.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha de Inicio:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Fin:");

        txtFechaRang1.setDateFormatString("yyyy-MM-dd");
        txtFechaRang1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtFechaRang2.setDateFormatString("yyyy-MM-dd");
        txtFechaRang2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnGenerarRep2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerarRep2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finanzas-y-negocios.png"))); // NOI18N
        btnGenerarRep2.setText("Generar Reporte");
        btnGenerarRep2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRep2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sección:");

        comboOficina2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboOficina2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botonGrupo2.add(recibida2);
        recibida2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recibida2.setForeground(new java.awt.Color(255, 255, 255));
        recibida2.setText("RECIBIDA");
        recibida2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botonGrupo2.add(remitida2);
        remitida2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remitida2.setForeground(new java.awt.Color(255, 255, 255));
        remitida2.setText("REMITIDA");
        remitida2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRangFecLayout = new javax.swing.GroupLayout(panelRangFec);
        panelRangFec.setLayout(panelRangFecLayout);
        panelRangFecLayout.setHorizontalGroup(
            panelRangFecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRangFecLayout.createSequentialGroup()
                .addGroup(panelRangFecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRangFecLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaRang1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRangFecLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(panelRangFecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRangFecLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRangFecLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(11, 11, 11)
                                .addComponent(txtFechaRang2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(btnGenerarRep2)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(panelRangFecLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(recibida2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(remitida2)
                .addGap(118, 118, 118))
        );
        panelRangFecLayout.setVerticalGroup(
            panelRangFecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRangFecLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelRangFecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaRang1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelRangFecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaRang2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarRep2))
                .addGap(5, 5, 5)
                .addGroup(panelRangFecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRangFecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recibida2)
                    .addComponent(remitida2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        JTextFieldDateEditor editor1 = (JTextFieldDateEditor) txtFechaRang1.getDateEditor();
        editor1.setEditable(false);
        JTextFieldDateEditor editor2 = (JTextFieldDateEditor) txtFechaRang2.getDateEditor();
        editor2.setEditable(false);
        AutoCompleteDecorator.decorate(comboOficina2);

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelRangFec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelFechEspc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnFechaEspc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRangoFech)
                        .addGap(76, 76, 76))))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechaEspc)
                    .addComponent(btnRangoFech))
                .addGap(18, 18, 18)
                .addComponent(panelFechEspc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRangFec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFechaEspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaEspcActionPerformed
        this.panelRangFec.setVisible(false);
        this.panelFechEspc.setVisible(true);
        this.limpiarEspc();
        this.cargarFecha();
    }//GEN-LAST:event_btnFechaEspcActionPerformed

    private void btnRangoFechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRangoFechActionPerformed
        this.panelRangFec.setVisible(true);
        this.panelFechEspc.setVisible(false);
        this.limpiarRang();
    }//GEN-LAST:event_btnRangoFechActionPerformed

    private void btnGenerarRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRep2ActionPerformed
        this.segundoReporte();
    }//GEN-LAST:event_btnGenerarRep2ActionPerformed

    private void btnGenerarRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRep1ActionPerformed
        this.primerReporte();
    }//GEN-LAST:event_btnGenerarRep1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonGrupo1;
    private javax.swing.ButtonGroup botonGrupo2;
    private javax.swing.JRadioButton btnFechaEspc;
    private javax.swing.JButton btnGenerarRep1;
    private javax.swing.JButton btnGenerarRep2;
    private javax.swing.JRadioButton btnRangoFech;
    private javax.swing.JComboBox<Oficina> comboOficina1;
    private javax.swing.JComboBox<Oficina> comboOficina2;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelFechEspc;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelRangFec;
    private javax.swing.JRadioButton recibida1;
    private javax.swing.JRadioButton recibida2;
    private javax.swing.JRadioButton remitida1;
    private javax.swing.JRadioButton remitida2;
    private com.toedter.calendar.JDateChooser txtFechaEspc;
    private com.toedter.calendar.JDateChooser txtFechaRang1;
    private com.toedter.calendar.JDateChooser txtFechaRang2;
    // End of variables declaration//GEN-END:variables

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    
    private void botones() {
        this.btnGenerarRep1.setOpaque(false);
        this.btnGenerarRep1.setContentAreaFilled(false);
        this.btnGenerarRep1.setBorderPainted(false);

        this.btnGenerarRep2.setOpaque(false);
        this.btnGenerarRep2.setContentAreaFilled(false);
        this.btnGenerarRep2.setBorderPainted(false);
    }

    private void limpiarEspc() {
        this.txtFechaEspc.setCalendar(null);
        this.comboOficina1.setSelectedIndex(0);
        this.botonGrupo1.clearSelection();
        objO = null;
        categoria = null;
    }

    private void limpiarRang() {
        this.txtFechaRang1.setCalendar(null);
        this.txtFechaRang2.setCalendar(null);
        this.comboOficina2.setSelectedIndex(0);
        this.botonGrupo2.clearSelection();
        objO = null;
        categoria = null;
    }

    private void cargarCombox() {
        this.comboOficina1.removeAllItems();
        this.comboOficina2.removeAllItems();
        Oficina objOficina = new Oficina();
        objOficina.setNombre("--Seleccione--");
        this.comboOficina1.addItem(objOficina);
        this.comboOficina2.addItem(objOficina);

        try {
            OficinaBo.obtenerListaComboOficina(this.comboOficina1, cargo);
            OficinaBo.obtenerListaComboOficina(this.comboOficina2, cargo);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void obtenerDatosCombo1() {
        if (this.comboOficina1.getItemAt(this.comboOficina1.getSelectedIndex()) != null) {
            this.objO = this.comboOficina1.getItemAt(this.comboOficina1.getSelectedIndex());
        }
    }

    private void obtenerDatosCombo2() {
        if (this.comboOficina2.getItemAt(this.comboOficina2.getSelectedIndex()) != null) {
            this.objO = this.comboOficina2.getItemAt(this.comboOficina2.getSelectedIndex());
        }
    }

    private void cargarFecha() {
        Calendar cal = Calendar.getInstance();
        Timestamp fecha_hora = new Timestamp(cal.getTimeInMillis());
        String fechaSistema = String.valueOf(fecha_hora);

        try {
            Date fechaParseada = new SimpleDateFormat("yyyy-MM-dd").parse(fechaSistema.substring(0, 10));
            this.txtFechaEspc.setDate(fechaParseada);
        } catch (Exception e) {
        }
    }

    private void obtenerCategoria1() {
        if (this.recibida1.isSelected()) {
            this.categoria = "Recibida";
        } 
        if (this.remitida1.isSelected()) {
            this.categoria = "Remitida";
        }
    }
    
    private void obtenerCategoria2() {
        if (this.recibida2.isSelected()) {
            this.categoria = "Recibida";
        } 
        if (this.remitida2.isSelected()) {
            this.categoria = "Remitida";
        }
    }

    private void primerReporte() {
        this.obtenerDatosCombo1();
        this.obtenerCategoria1();
        if (!((JTextField) this.txtFechaEspc.getDateEditor().getUiComponent()).getText().trim().equals("")) {
            try {
                if (this.comboOficina1.getSelectedIndex() == 0 && this.categoria == null) {
                    RepFech report = new RepFech();
                    report.verReporte(cargo, (String) ((JTextField) this.txtFechaEspc.getDateEditor().getUiComponent()).getText());
                }
                if (this.comboOficina1.getSelectedIndex() != 0 && this.categoria == null) {
                    RepFechSecc report = new RepFechSecc();
                    report.verReporte(cargo, (String) ((JTextField) this.txtFechaEspc.getDateEditor().getUiComponent()).getText(),
                            this.objO.getNombre());
                }
                if (this.comboOficina1.getSelectedIndex() == 0 && this.categoria != null) {
                    RepFechCat report = new RepFechCat();
                    report.verReporte(cargo, (String) ((JTextField) this.txtFechaEspc.getDateEditor().getUiComponent()).getText(), this.categoria);
                }
                if (this.comboOficina1.getSelectedIndex() != 0 && this.categoria != null) {
                    RepFechSeccCat report = new RepFechSeccCat();
                    report.verReporte(cargo, (String) ((JTextField) this.txtFechaEspc.getDateEditor().getUiComponent()).getText(), 
                            this.categoria, this.objO.getNombre());
                }
                this.limpiarEspc();
                this.cargarFecha();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Usted no a elegido una fecha específica.", "MENSAJE --> REPORTE FECHA", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void segundoReporte() {
        this.obtenerDatosCombo2();
        this.obtenerCategoria2();
        if (!(((JTextField) this.txtFechaRang1.getDateEditor().getUiComponent()).getText().trim().equals("")
                || ((JTextField) this.txtFechaRang2.getDateEditor().getUiComponent()).getText().trim().equals(""))) {
            try {
                if (this.comboOficina2.getSelectedIndex() == 0 && this.categoria == null) {
                    RepFechRang report = new RepFechRang();
                    report.verReporte(cargo, (String) ((JTextField) this.txtFechaRang1.getDateEditor().getUiComponent()).getText(),
                            (String) ((JTextField) this.txtFechaRang2.getDateEditor().getUiComponent()).getText());
                }
                if (this.comboOficina2.getSelectedIndex() != 0 && this.categoria == null) {
                    RepFechRanSecc report = new RepFechRanSecc();
                    report.verReporte(cargo, (String) ((JTextField) this.txtFechaRang1.getDateEditor().getUiComponent()).getText(),
                            (String) ((JTextField) this.txtFechaRang2.getDateEditor().getUiComponent()).getText(), this.objO.getNombre());
                }
                if (this.comboOficina2.getSelectedIndex() == 0 && this.categoria != null) {
                    RepFechRanCat report = new RepFechRanCat();
                    report.verReporte(cargo, (String) ((JTextField) this.txtFechaRang1.getDateEditor().getUiComponent()).getText(),
                            (String) ((JTextField) this.txtFechaRang2.getDateEditor().getUiComponent()).getText(), this.categoria);
                }
                if (this.comboOficina2.getSelectedIndex() != 0 && this.categoria != null) {
                    RepFechRanCatSecc report = new RepFechRanCatSecc();
                    report.verReporte(cargo, (String) ((JTextField) this.txtFechaRang1.getDateEditor().getUiComponent()).getText(),
                            (String) ((JTextField) this.txtFechaRang2.getDateEditor().getUiComponent()).getText(), this.categoria,
                            this.objO.getNombre());
                }
                this.limpiarRang();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Usted no a elegido una rango de fecha.", "MENSAJE --> REPORTE FECHA", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
